cinema/cinema/Models/Arrangement.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace cinema.Models;

public class Arrangement
{
    [Key]
    public int Id { get; set; }
    public double Price { get; set; }
    public string Description { get; set; }
}

cinema/cinema/Models/Ticket.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace cinema.Models;

public class Ticket
{
    [Key]
    public int Id { get; set; }
    public Show show { get; set; }
    public int SeatRow { get; set; }
    public int SeatNr { get; set; }
    public bool ChildDiscount { get; set; }
    public bool StudentDiscount { get; set; }
    public bool SeniorDiscount { get; set; }
    public int Code { get; set; }
    public bool CodeUsed { get; set; }
    public bool Popcorn { get; set; }

    public Arrangements Arrangements { get; set; }
}

cinema/cinema/Controllers/PaymentController.cs
using System.Text.Json;
using cinema.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe;
using Stripe.Checkout;

namespace cinema.Controllers;

public class PaymentController : Controller
{
    private readonly IConfiguration _config;
    private readonly CinemaContext _context;
    

    public PaymentController(IConfiguration config, CinemaContext context)
    {
        _config = config;
        _context = context;
        StripeConfiguration.ApiKey = _config["StripeKey"];

    }

    [HttpPost("create-checkout-session")]
    public ActionResult CreateCheckoutSession([FromForm] int orderid)
    {
        var order = _context.Orders.First(o => o.Id == orderid);
        var show = _context.Shows.Include(s => s.Movie).First(s => s.Id == order.ShowId);
        var cost = (int) order.Cost * 100;
        var options = new SessionCreateOptions
        {
            LineItems = new List<SessionLineItemOptions>
            {
                new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = cost,
                        Currency = "eur",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = "Bestelling :"+show.Movie.Name,
                        },

                    },
                    Quantity = 1,
                },
            },
            Mode = "payment",
            SuccessUrl = "https://localhost:7184/payment/PaymentSucces?id="+orderid,
            CancelUrl = "https://localhost:7184/error",
        };

        var service = new SessionService();
        Session session = service.Create(options);

        Response.Headers.Add("Location", session.Url);
        return new StatusCodeResult(303);
    }

    [HttpGet]
    public RedirectToActionResult PaymentSucces(
        [FromQuery] int id)
    {
        var order = _context.Orders.First(o => o.Id == id);
        order.IsPayed = true;
        _context.Orders.Update(order);
        _context.SaveChanges();
        return RedirectToAction("Index", "Tickets", new {id = id});
    }
}

cinema/cinema/Controllers/TicketsController.cs
#nullable disable
using System.Linq;
using cinema.Data;
using Microsoft.AspNetCore.Mvc;
using cinema.Models;
using cinema.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Protocols;
using System.Text.Json;
using Stripe;

namespace cinema.Controllers
{
    public class TicketsController : Controller
    {
        private readonly CinemaContext _context;

        private readonly ITicketService _ticketService;

        private readonly IPriceCalculatingService _priceCalculatingService;

        private readonly IShowService _showService;

        private readonly IMovieService _movieService;

        private readonly IConfiguration _config;


        public TicketsController(IPriceCalculatingService priceCalculatingService, ITicketService ticketService,
            IMovieService movieService, CinemaContext context, IShowService showService, IConfiguration config)
        {
            _ticketService = ticketService;
            _movieService = movieService;
            _context = context;
            _showService = showService;
            _config = config;
            _priceCalculatingService = priceCalculatingService;
        }

        [HttpGet]
        [Route("/tickets")]
        [Route("/tickets/index")]
        public IActionResult Index(int id)
        {
            ViewBag.StripePublishKey = _config["StripePubKey"];
            var order = _context.Orders.First(o => o.Id == id);
            var ticketIdsString = order.SerializedTicketIds;
            var ticketIds =  JsonSerializer.Deserialize<int[]>(ticketIdsString);
            var tickets = new List<Ticket>();
            foreach (var ticketId in ticketIds)
            {
                tickets.Add(_context.Tickets.Include(t => t.show.Movie).First(t => t.Id == ticketId));
            }

            ViewBag.Cost = order.Cost;
            ViewBag.OrderId = id;
            ViewBag.IsPayed = order.IsPayed;
            return View(tickets);
        }


        [HttpGet]
        [Route("/tickets/arrangements")]
        public IActionResult Arrangements([FromQuery] int showId)
        {
            Movie movie = _movieService.GetMovieFromShow(showId);
            ViewBag.Movie = movie;
            ViewBag.ShowId = showId;
            ViewBag.Vip = cinema.Arrangements.vip;
            ViewBag.Normal = cinema.Arrangements.normale;
            ViewBag.ChildrenParty = cinema.Arrangements.kinderfeestje;
            return View();
        }

        [HttpGet]
        [Route("/tickets/quantity")]
        public IActionResult Quantity([FromQuery] int showId, [FromQuery] Arrangements arrangement)
        {
            Movie movie = _movieService.GetMovieFromShow(showId);
            ViewBag.Movie = movie;
            ViewBag.ShowId = showId;
            ViewBag.Arrangement = arrangement;
            return View();
        }


        [HttpGet]
        [Route("/tickets/create")]
        public IActionResult Discount(
            [FromQuery] int showId,
            [FromQuery] int quantity,
            [FromQuery] Arrangements arrangement)
        {
            ViewBag.show = showId;
            ViewBag.price = _priceCalculatingService.pricePerTicket(showId);
            ViewBag.totalPrice = _priceCalculatingService.ticketCost(quantity, showId);
            ViewBag.quantity = quantity;
            ViewBag.Arrangement = arrangement;
            return View();
        }

        [HttpGet]
        [Route("/tickets/reservation")]
        public IActionResult Reservation(
            [FromQuery] int showId,
            [FromQuery] int quantity,
            [FromQuery] int childDiscount,
            [FromQuery] int studentDiscount,
            [FromQuery] int seniorDiscount,
            [FromQuery] int popcorn,
            [FromQuery] Arrangements arrangement)

        {
            ViewBag.quantity = quantity;
            ViewBag.showId = showId;
            ViewBag.movieName = _showService.getShowById(showId).Movie.Name;
            ViewBag.threeD = _showService.getShowById(showId).ThreeD;
            ViewBag.childDiscount = childDiscount;
            ViewBag.studentDiscount = studentDiscount;
            ViewBag.seniorDiscount = seniorDiscount;
            ViewBag.popcorn = popcorn;


            ViewBag.Arrangement = arrangement;

            var totalCost = _priceCalculatingService.ticketCost(quantity, showId);
            var discount = _priceCalculatingService.Discount(childDiscount, studentDiscount, seniorDiscount);
            var premium = _priceCalculatingService.Premium(popcorn);
            var arrangementCost = _priceCalculatingService.ArrangementCost(arrangement);

            ViewBag.arrangementCost = arrangementCost;
            ViewBag.totalCost = totalCost;
            ViewBag.Discount = discount;
            ViewBag.Popcorn = premium;
            ViewBag.OrderCost = _priceCalculatingService.OrderCost(discount, premium, totalCost, arrangementCost);
            return View();
        }

        [HttpPost]
        [Route("/tickets/create")]
        public IActionResult Create(
            [FromForm] int showId,
            [FromForm] int quantity,
            [FromForm] int childDiscount,
            [FromForm] int seniorDiscount,
            [FromForm] int studentDiscount,
            [FromForm] int popcorn,
            [FromForm] Arrangements arrangement,
            [FromForm] double orderCost
        )
        {
            var tickets = _ticketService.CreateTickets(
                showId,
                quantity,
                childDiscount,
                seniorDiscount,
                studentDiscount,
                popcorn,
                arrangement
            );
            var myTicketsId = new List<int>();
            foreach (var ticket in tickets)
            {
                myTicketsId.Add(ticket.Id);
            }

            var order = new TicketOrder()
            {
                Cost = orderCost,
                SerializedTicketIds = JsonSerializer.Serialize(myTicketsId),
                ShowId = showId
            };
            _context.Orders.Add(order);
            _context.SaveChanges();


            TempData["myTickets"] = myTicketsId;

            return RedirectToAction("Index", new
            {
                id = order.Id
            });
        }

        [HttpPost]
        [Route("/tickets/betalen")]
        public IActionResult Payment(TicketOrder order)
        {
            ViewBag.order = order;
            ViewBag.StripePubKey = _config["StripePubKey"];
            return View();
        }

        [HttpPost]
        public void Pay(string stripeToken, TicketOrder order)
        {
            Stripe.StripeConfiguration.SetApiKey(_config["StripePubKey"]);
            Stripe.StripeConfiguration.ApiKey = _config["StripeKey"];

            var myCharge = new Stripe.ChargeCreateOptions();
            // always set these properties
            myCharge.Amount = (long?) (order.Cost * 100);
            myCharge.Currency = "EUR";
            myCharge.Description = order.Id.ToString();
            myCharge.Source = stripeToken;
            myCharge.Capture = true;
            var chargeService = new Stripe.ChargeService();
            Charge stripeCharge = chargeService.Create(myCharge);
            Console.WriteLine(JsonSerializer.Serialize(stripeCharge));

            RedirectToAction("Create");
        }
    }
}

cinema/cinema/Views/Tickets/Arrangements.cshtml
@model dynamic

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Maak een keuze uit één van onze arrangementen</h2>
    <div class="row my-5">
        <div class="col-md-4">
            <div class="card h-100 text-white">
                <a asp-action="quantity" asp-route-showId="@ViewBag.ShowId" asp-route-arrangement="@ViewBag.Normal" class="text-decoration-none">
                    <img class="card-img" src="https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="Normale kaartjes">
                    <div class="card-img-overlay d-flex  justify-content-between align-items-center">
                        <div class="w-100">
                            <h2 class="card-title text-white text-center shadow">Normale kaartjes</h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <ul class=" text-dark">
                            <li>
                                comfortabele seats
                            </li>
                        </ul>
                    </div>

                </a>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card h-100 text-white">
                <a asp-action="quantity" asp-route-showId="@ViewBag.ShowId" asp-route-arrangement="@ViewBag.Vip" class="text-decoration-none">
                    <img class="card-img" src="https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2376&q=80" alt="VIP">
                    <div class="card-img-overlay d-flex  justify-content-between align-items-center">
                        <div class="w-100">
                            <h2 class="card-title text-white text-center shadow">VIP kaartjes</h2>
                        </div>
                    </div>
                    <div class="card-body text-dark d-flex justify-content-between flex-column">
                        <ul class=" text-dark">
                            <li>
                                ontvangst + welkomstdrankje
                            </li>
                            <li>
                                toegang tot vip lounge
                            </li>
                            <li>
                                hapje + drankje tijdens de film
                            </li>

                            <li>
                                comfortabele vip-seats
                            </li>
                        </ul>
                        <h3>
                            + €4,-
                        </h3>
                    </div>

                </a>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-white h-100">
                <a asp-action="quantity" asp-route-showId="@ViewBag.ShowId" asp-route-arrangement="@ViewBag.ChildrenParty" class="text-decoration-none">
                    <img class="card-img" src="https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2371&q=80" alt="Kinderen">
                    <div class="card-img-overlay d-flex  justify-content-between align-items-center">
                        <div class="w-100">
                            <h2 class="card-title text-white text-center shadow">Kinderfeestje</h2>
                        </div>
                    </div>
                    <div class="card-body text-dark d-flex justify-content-between flex-column">
                        <ul >
                            <li>
                                maximale leeftijd is 12
                            </li>
                            <li>
                                film + popcorn (medium geen zout)
                            </li>
                            <li>
                                cadeautje
                            </li>

                        </ul>
                        <h3>+ €5,-</h3>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

cinema/cinema/Views/Tickets/Discount.cshtml
@using cinema.Models
@model cinema.Models.Ticket

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int quantity = ViewBag.quantity;
}

<h2 class="mt-5">Kortingen</h2>
<hr/>

<form method="get" asp-action="Reservation">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" name="quantity" value="@quantity">
    <input type="hidden" name="showId" value="@ViewBag.show">
    <input type="hidden" name="arrangement" value="@ViewBag.Arrangement">
    <div class="mb-4">
        <label class="form-check-label">
            Kinder korting (- €1.50)
            <select name="childDiscount" id="childDiscount">
                @for (int discount = 0; discount < @quantity + 1; discount++)
                {
                    <option value="@discount">@discount</option>
                }
            </select>
        </label>
    </div>
    <div class="mb-4">
        <label class="form-check-label">
            Studenten korting (- €1.50)
            <select name="studentDiscount" id="studentDiscount">
                @for (int discount = 0; discount < @quantity + 1; discount++)
                {
                    <option value="@discount">@discount</option>
                }
            </select>
        </label>
    </div>
    <div class="mb-4">
        <label class="form-check-label">

            Senioren korting (- €1.50)
            <select name="seniorDiscount" id="seniorDiscount">
                @for (int discount = 0; discount < @quantity + 1; discount++)
                {
                    <option value="@discount">@discount</option>
                }
            </select>
        </label>
    </div>
    <h3 class="mt-5">Extra opties</h3>
    <hr>
    <div class="mb-4">
        <label class="form-check-label">
            Popcorn (+ €2.5)
            <select name="popcorn" id="popcorn">
                @for (int discount = 0; discount < @quantity + 1; discount++)
                {
                    <option value="@discount">@discount</option>
                }
            </select>
        </label>
    </div>
    <div class="form-group">
        <input type="submit" value="Volgende" class="btn btn-primary"/>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

cinema/cinema/Views/Tickets/Index.cshtml
@model IEnumerable<cinema.Models.Ticket>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h3 class="h1 my-4">Bedankt voor je reservering!</h3>
    <div class="row my-5">
        <p> Je kan de kaartjes hieronder terugvinden.</p>
        <div class="mx-3 w-100 alert alert-warning">
            <strong>Vergeet niet de kaartjes af te drukken, ongeacht of ze je nu direct betaald, of pas in de bioscoop</strong>

        </div>
        <button class="print btn btn-secondary mx-3 w-100">
            <strong>Print de tickets</strong>
        </button>

    </div>
    @if (!ViewBag.IsPayed)
    {

        <div class="row my-5">

            <div class="col-md-4">

                <div class="card h-100 text-white">
                    <div class="card-header">

                        <h2 class="card-title text-black text-center ">Betaal direct</h2>
                    </div>
                    <img class="card-img paycard_img" src="/images/digital_payment.jpg" alt="Pin betalen">
                    <div class="card-body">
                        <ul class=" text-dark">
                            <li>
                                Je kaartjes zijn gereserveerd
                            </li>
                            <li>
                                Je kaartjes zijn <strong>wel</strong> betaald; je kan direct doorlopen
                            </li>
                        </ul>
                    </div>
                    <div class="card-footer">
                        <form asp-controller="Payment" asp-action="CreateCheckoutSession" method="POST">
                            <input type="hidden" name="orderid" value="@ViewBag.OrderId">
                            <div class="form-group">
                                <input type="submit" value="Betalen" class="btn btn-primary"/>
                            </div>
                        </form>

                    </div>


                </div>
            </div>
            <div class="col-md-4">

                <div class="card h-100 text-white">
                    <div class="card-header">
                        <h2 class="card-title text-black text-center">Pinbetaling in bios</h2>
                    </div>
                    <img class="card-img paycard_img" src="/images/analog_payment.jpg" alt="Pin betalen">

                    <div class="card-body">
                        <ul class=" text-dark">
                            <li>
                                Je kaartjes zijn gereserveerd
                            </li>
                            <li>
                                Je kaartjes zijn <strong>niet</strong> betaald; daarvoor moet je nog langs de kassa
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    }


    <div class="row tickets">
        @foreach (var item in Model)
        {
            <div class="col-md-3 mb-4">
                <div class="card ticket">
                    <div class="card-body">
                        <h4 class="card-title">@item.show.Movie.Name</h4>

                        @if (item.Arrangements == Arrangements.normale)
                        {
                            <h5>Regulier kaartje</h5>
                        }
                        else
                        {
                            <h5>@item.Arrangements kaartje</h5>
                        }
                        <img src="@item.show.Movie.Poster" style="max-height: 600px;" alt="@item.show.Movie.Name" class="card-img-top">
                        <br><br>
                        <p class="card-text">Zaal: @item.show.Room</p>
                        <p class="card-text">Datum: @item.show.StartTime</p>
                        @if (@item.show.Break)
                        {
                            <p class="card-text">Pauze: Ja </p>
                        }
                        else
                        {
                            <p class="card-text">Pauze: Nee </p>
                        }
                        <hr>
                        <h5>Stoelen</h5>
                        <p class="card-text">Rij: @item.SeatRow</p>
                        <p class="card-text">Nummer: @item.SeatNr</p>
                        <hr>
                        <h4 class="card-text">Code: @item.Code</h4>
                        @if (ViewBag.IsPayed)
                        {
                            
                            <div class="alert alert-success">Betaald</div>
                        }

                    </div>
                </div>
            </div>
        }

        <script >
        
        
        var tickets = document.querySelector('.tickets');
        document.querySelector('.print').addEventListener('click', function (){
                             var WinPrint = window.open('', '', 'left=0,top=0,width=800,height=900,toolbar=0,scrollbars=0,status=0');
                                           WinPrint.document.write(tickets.innerHTML);
                                           WinPrint.document.close();
                                           WinPrint.focus();
                                           WinPrint.print();
                        })
                      
            document.querySelectorAll('.ticket').forEach(function (value, key, parent){
                value.addEventListener('click', function (){
                     var WinPrint = window.open('', '', 'left=0,top=0,width=800,height=900,toolbar=0,scrollbars=0,status=0');
                                   WinPrint.document.write(value.innerHTML);
                                   WinPrint.document.close();
                                   WinPrint.focus();
                                   WinPrint.print();
                                   // WinPrint.close();
                })
              
            });
        </script>
    </div>
</div>

cinema/cinema/Views/Tickets/Payment.cshtml
@model dynamic

@{
    ViewBag.Title = "Betaling";
    Layout = "_Layout";
}

<h2>title</h2>
<form action="/tickets/betalen" method="POST">
    <article>
        <label>Amount: @ViewBag.details.TotalPrice</label>
    </article>
    <script src="//checkout.stripe.com/v2/checkout.js"
            class="stripe-button"
            data-key="@ViewBag.StripePubKey"
            data-locale="auto"
            data-description="Sample Charge"
            data-amount="@ViewBag.details.TotalPrice">
    </script>
</form>

cinema/cinema/Views/Tickets/Quantity.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="@ViewBag.Movie.Poster" alt="@ViewBag.Movie.Name" class="img-fluid">
        </div>
        <div class="col-md-6">

            <h3 class="card-title">@ViewBag.Movie.Name</h3>
            <p class="card-text">@ViewBag.Movie.Description</p>
            <hr>
            <div>
                <h4>Hoeveel @ViewBag.Arrangement kaartjes wilt u kopen?</h4>

                <form method="get" asp-action="Discount">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" name="showId" value="@ViewBag.ShowId">
                    <input type="hidden" name="arrangement" value="@ViewBag.Arrangement">
                    <select name="quantity" id="quantity">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>

                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                    </select>
                    <div class="form-group my-5">
                        <input type="submit" value="Volgende" class="btn btn-primary"/>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

cinema/cinema/Views/Tickets/Reservation.cshtml
@using cinema.Models
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Betalings overzicht</h2>
<hr>
<p>Film: <strong>@ViewBag.movieName</strong></p>
<p>3D: 
@if (@ViewBag.threeD)
{
    <strong>ja (+ €3.50 per kaartje)</strong>
}
else
{
    <strong>nee</strong>
}
    </p>
<hr>
<div>Aantal kaartjes: <strong>@ViewBag.quantity</strong></div>
<p>Type:<strong> @ViewBag.Arrangement</strong> (+ € @ViewBag.arrangementCost per kaartje)</p>
<hr>
<p>Popcorn: <strong>+ € @ViewBag.popcorn </strong></p>
<p>Korting: <strong>- €@ViewBag.discount </strong></p>
<hr>
<h5>Totaal te betalen <strong>€ @ViewBag.OrderCost</strong></h5> <br>

<form method="post" asp-action="create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" value="@ViewBag.showId" name="showId">
    <input type="hidden" value="@ViewBag.quantity" name="quantity">
    <input type="hidden" value="@ViewBag.Arrangement" name="arrangement">
    <input type="hidden" value="@ViewBag.childDiscount" name="childDiscount">
    <input type="hidden" value="@ViewBag.studentDiscount" name="studentDiscount">
    <input type="hidden" value="@ViewBag.seniorDiscount" name="seniorDiscount">
    <input type="hidden" value="@ViewBag.popcorn" name="popcorn">
    <input type="hidden" value="@ViewBag.OrderCost" name="orderCost">
    <div class="form-group">
        <input type="submit" value="Bestellen" class="btn btn-primary"/>
    </div>
</form>