cinema/cinema/Models/Show.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace cinema.Models;

public class Show
{
    [Key]
    public int Id { get; set; }
    public bool ThreeD { get; set; }
    public int Room { get; set; }
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
    public DateTime StartTime { get; set; }
    public bool Break { get; set; }
    public Movie Movie { get; set; }    
}

cinema/cinema/Controllers/MoviesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cinema.Data;
using cinema.Models;

namespace cinema.Controllers
{
    public class MoviesController : Controller
    {
        private readonly CinemaContext _context;

        public MoviesController(CinemaContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movies.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.Name == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Director,Cast,ReleaseYear,CountryOfOrigin,Length,Genre,Poster,Language,ThreeD")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Description,Director,Cast,ReleaseYear,CountryOfOrigin,Length,Genre,Poster,Language,ThreeD")] Movie movie)
        {
            if (id != movie.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.Name == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(string id)
        {
            return _context.Movies.Any(e => e.Name == id);
        }
    }
}

cinema/cinema/Controllers/ShowsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cinema.Data;
using cinema.Models;
using cinema.Services;
using cinema.Filters;

namespace cinema.Controllers
{
    public class ShowsController : Controller
    {
        private readonly CinemaContext _context;
        private readonly ShowService _showService;

        public ShowsController(CinemaContext context, IShowService service)
        {
            
            _context = context;
            _showService = (ShowService) service;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {
            
            var showList =  _context.Shows.Include(s => s.Movie).ToList();
            var showPerMoviePerDateDict = _showService.GetShowsPerMoviePerDay(showList);

            ShowsFilter filter = new ShowsFilter(showList);
            ViewData["ShowsFilter"] = filter;

            return View(showPerMoviePerDateDict);
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (ModelState.IsValid)
            {
                _context.Add(show);
                await _context.SaveChangesAsync();
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows.FindAsync(id);
            if (show == null)
            {
                return NotFound();
            }
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(show);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _context.Shows.FindAsync(id);
            _context.Shows.Remove(show);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowExists(int id)
        {
            return _context.Shows.Any(e => e.Id == id);
        }

        //GET: Shows/Daily
        public IActionResult Daily()
        {
            return View(_context.Shows.Include(s => s.Movie).Where(s => s.StartTime > DateTime.Now).Where(s => s.StartTime.Date == DateTime.Today.Date).ToList());
        }

        [HttpGet, HttpPost, ActionName("Filter")]
        public IActionResult Filter()
        {
            List<Show> shows = _context.Shows.Include(s => s.Movie).Where(s => s.StartTime > DateTime.Now).ToList();
            ShowsFilter filter = new ShowsFilter(shows);      
            if(Request.Method == HttpMethod.Post.Method)
            {
                if(Request.Form["search"] != "")
                    filter.input = Request.Form["search"];
                if (Request.Form["len"] != "")
                    filter.maxlength = Convert.ToDouble(Request.Form["len"]);
                if (Request.Form["date"] != "")
                    filter.date = Convert.ToDateTime(Request.Form["date"]);
                if (Request.Form["threed"] != "")
                    if (Request.Form["threed"] == "on")
                        filter.threed = true;
                    else
                        filter.threed = false;
                foreach (string language in filter.languages.Keys)
                    if (Request.Form[language] == "on")
                        filter.languages[language] = true;
                    else
                        filter.languages[language] = false;
                foreach (string genre in filter.genres.Keys)
                    if (Request.Form[genre] == "on")
                        filter.genres[genre] = true;
                    else
                        filter.genres[genre] = false;
                foreach (string kijkwijzer in filter.kijkwijzers.Keys)
                    if (Request.Form[kijkwijzer] == "on")
                        filter.kijkwijzers[kijkwijzer] = true;
                    else
                        filter.kijkwijzers[kijkwijzer] = false;
            }
            shows = filter.Apply(shows);
            ViewData["ShowsFilter"] = filter;
            return View("Index", _showService.GetShowsPerMoviePerDay(shows));
        }
    }
}

cinema/cinema/Views/Shows/Create.cshtml
@model cinema.Models.Show

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">   

<h1>Create</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ThreeD" /> @Html.DisplayNameFor(model => model.ThreeD)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Room" class="control-label"></label>
                <input asp-for="Room" class="form-control" />  @Html.DisplayNameFor(model => model.Room)
                <span asp-validation-for="Room" class="text-danger"></span> 
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />  @Html.DisplayNameFor(model => model.StartTime)
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Break" /> @Html.DisplayNameFor(model => model.Break)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Movie" /> @Html.DisplayNameFor(model => model.Movie)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Index", "Index")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

cinema/cinema/Views/Shows/Daily.cshtml
@using cinema.Models
@model IEnumerable<cinema.Models.Show>

@{
    ViewData["Title"] = "Films";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<h1></h1>

@* Date picker *@


@* Left bar with all movies that day *@
@{
    List<Movie> Movies = new List<Movie>();
    foreach(Show show in Model){
        if(!Movies.Contains(show.Movie))
            Movies.Add(show.Movie);
    }
}

<ul style="list-style-type:none;">
@foreach(Movie movie in Movies){
    <li>@Html.DisplayFor(Movie => movie.Name)</li>;
}
</ul>


@* Main screen with all shows per movie for selected date *@
@foreach(Movie movie in Movies){
    <div>
        <h1>@Html.DisplayFor(Movie => movie.Name)</h1>
        <ul style="list-style-type:none;">
            @{
                foreach(var show in Model){
                    if(show.Movie == movie)
                    {
                        <li><a asp-controller="Tickets" asp-action="Quantity" asp-route-id="@show.Id">@show.StartTime.ToString("HH:mm")</a></li>
                    }
                }
            }
        </ul>
    </div>
}

cinema/cinema/Views/Shows/Delete.cshtml
@model cinema.Models.Show

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThreeD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThreeD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Break)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Break)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

cinema/cinema/Views/Shows/Details.cshtml
@model cinema.Models.Show

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThreeD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThreeD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Break)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Break)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

cinema/cinema/Views/Shows/Edit.cshtml
@model cinema.Models.Show

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ThreeD" /> @Html.DisplayNameFor(model => model.ThreeD)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Room" class="control-label"></label>
                <input asp-for="Room" class="form-control" />
                <span asp-validation-for="Room" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Break" /> @Html.DisplayNameFor(model => model.Break)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

cinema/cinema/Views/Shows/Index.cshtml
@using cinema.Models
@using cinema.Services
@model Dictionary<DateOnly, Dictionary<cinema.Models.Movie, List<cinema.Models.Show>>>

@{
    ViewData["Title"] = "Voorstellingen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/shows.css" asp-append-version="true"/>
}

<h1>Voorstellingen</h1>

@using cinema.Filters
@{
    ShowsFilter? filter = (ShowsFilter?) ViewData["ShowsFilter"];
    //if (filter == null) filter = new ShowsFilter(Model.Keys.ToList());
    if(filter != null)
    {
        <form method="post" asp-controller="Shows" asp-action="Filter">
            <label for="search">Search</label>
            <input type="text" id="search" name="search" value="@filter.input">
            <label for="len">Length</label>
            <input type="range" id="len" name="len" min="0" max="@filter.maxselectablelength" value="@filter.maxlength">
            <label for="date">Date</label>
            <input type="date" id="date" name="date">
            <label for="threed">3D</label>
            <input type="checkbox" id="threed" name="threed" checked="@filter.threed">
            <label>Languages</label>
            @foreach(string language in filter.languages.Keys){
                <label for="@language">@language</label>
                <input type="checkbox" id="@language" name="@language" checked="@filter.languages[language]">
            }
            <label>Genres</label>
            @foreach(string genre in filter.genres.Keys){
                <label for="@genre">@genre</label>
                <input type="checkbox" id="@genre" name="@genre" checked="@filter.genres[genre]">
            }
            <label>Kijkwijzers</label>
            @foreach(string kijkwijzer in filter.kijkwijzers.Keys){
                <label for="@kijkwijzer">@kijkwijzer</label>
                <input type="checkbox" id="@kijkwijzer" name="@kijkwijzer" checked="@filter.kijkwijzers[kijkwijzer]">
            }
            <input type="submit" value="Search">
        </form>
    }
}

<div class="container-fluid">
    
    @foreach (var date in Model.Keys)
    {
        //return if the movies are older than today
        if (date < DateOnly.FromDateTime(DateTime.Now)) continue;
        
        <div class="date-row"><h2 class="date-row-date">
            
            @date
        </h2></div>
        
        <div>
            <div class="shows_container">
                @foreach (var movie in Model[@date].Keys)
                {
      
                        <div class="shows_page_show_card">
                            <img class="show_image" src="@movie.Poster">
                            <div class="show_times">
                                @foreach (var show in Model[@date][@movie])
                                {
                                    <form method="get" class="show-button" asp-controller="Tickets" asp-action="Arrangements" >
                                        <input type="hidden" name="showId" value="@show.Id"/>
                                        
                                        <button class="btn btn-primary"  type="submit">
                                            @TimeOnly.FromDateTime(show.StartTime).Hour.00 in zaal @show.Room
                                        </button>
                                        
                                    </form>
                                }
                            </div>
                        
                        <form method="get" class="info-button">
                            <button class="btn btn-secondary w-100" asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Name">Film-info</button>
                        </form>
</div>
  
                }
            </div>
        </div>
    }
</div>